version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/post/db

volumes: 
  pgdata: